#Default Config.yml
#Scale can range from CLOSEST, CLOSE, NORMAL, FAR, FARTHEST
faceSize: 4 #How big do you want the face images to be?
scale: CLOSEST #This is the view for the player when viewing the map. CLOSEST will give the player the smallest possible view of the world.
