#Default Config.yml
#Scale can range from CLOSEST, CLOSE, NORMAL, FAR, FARTHEST
faceSize: 4 #How big do you want the face images to be?
scale: CLOSEST #This is the view for the player when viewing the map. CLOSEST will give the player the smallest possible view of the world.
map-display-name: '&eMarauders Map' #Name of the map
individual-scales: true #Do you want each map to preserve its scale even though you changed it in the config?
show-update-message: true #Do you want to see the update message that notifies you of an update?
